name = "RenderPDDL"
uuid = "8f72e95f-8ea1-4af3-8b89-086f52abff52"
authors = ["Xuan <tanqazx@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
PDDL = "2c8894f9-daa1-498a-9e3a-26edd9623db8"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"

[compat]
Makie = "0.15"
PDDL = "0.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
